---
# tasks file for hoplacloud.wordpress

- name: Init vars
  set_fact:
    wp_password: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters,digits,hexdigits,punctuation') }}"
    db_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits,hexdigits') }}"
    vhost_user: "{{ vhost_url | regex_replace('\\.') | truncate(13, True, '') }}"
    vhost_domain: "{{ vhost_url | regex_replace('([^\\.]*)\\.(.+)$', '\\2') }}"
    vhost_sdomain: "{{ vhost_url | regex_replace('([^\\.]*)\\.(.+)$', '\\1') }}"

- name: Set vhost_path
  set_fact:
    vhost_path: "/var/www/custs/{{vhost_domain}}/{{vhost_sdomain}}"
    vhost_conf_file: "{{vhost_domain}}_{{vhost_sdomain}}"

- name: Create mysql database
  mysql_db:
    name: "{{ vhost_user }}"
    state: present

- name: Create mysql user
  mysql_user:
    state: present
    name: "{{ vhost_user }}"
    password: "{{ db_password }}"
    login_host: localhost
    priv: '{{ vhost_user }}.*:ALL'

- name: Creating websites directory
  file:
    path: "{{ vhost_path }}"
    state: directory

- name: Download WordPress
  get_url:
    url: "https://wordpress.org/latest.tar.gz"
    dest: "/tmp/wordpress.tar.gz"
    validate_certs: "no"

- name: Extract WordPress
  unarchive:
    src: "/tmp/wordpress.tar.gz"
    dest: "{{ vhost_path }}/"
    remote_src: yes

- name: Copy vhost config
  copy:
    src: "files/vhost.conf"
    dest: "/etc/apache2/sites-available/{{ vhost_conf_file }}.conf"

- name: Update Apache vhost [1/5]
  lineinfile:
    dest: "/etc/apache2/sites-available/{{ vhost_conf_file }}.conf"
    regexp: '"vhost_path"'
    line: '"{{ vhost_path }}"'

- name: Update Apache vhost [2/5]
  lineinfile:
    dest: "/etc/apache2/sites-available/{{ vhost_conf_file }}.conf"
    regexp: '"vhost_url"'
    line: '"{{ vhost_url }}"'

- name: Update Apache vhost [3/5]
  lineinfile:
    dest: "/etc/apache2/sites-available/{{ vhost_conf_file }}.conf"
    regexp: '"php_version"'
    line: '"{{ php_version }}"'

- name: Update Apache vhost [4/5]
  lineinfile:
    dest: "/etc/apache2/sites-available/{{ vhost_conf_file }}.conf"
    regexp: '"user_email"'
    line: '"{{ user_email }}"'

- name: Update Apache vhost [5/5]
  lineinfile:
    dest: "/etc/apache2/sites-available/{{ vhost_conf_file }}.conf"
    regexp: '"vhost_conf_file"'
    line: '"{{ vhost_conf_file }}"'

- name: Copy sample config file
  copy:
    remote_src: yes
    src: "{{ vhost_path }}/wp-config-sample.php"
    dst: "{{ vhost_path }}/wp-config.php"

- name: Update WordPress config file
  lineinfile:
    dest: "{{ vhost_path }}/wp-config.php"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{ db_name }}}');"}
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{ db_name }}');"}
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{ db_password }}');"}
