---
- hosts: localhost
  remote_user: root
  pre_tasks:
    - name: Add mariadb Repository Key Ubuntu 18.04
      shell: "apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8"
      when: "'mariadb-server' in mysql_packages and 'bionic' in ansible_distribution_release"

    - name: Add mariadb Repository Key Ubuntu 20.04
      shell: "apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 F1656F24C74CD1D8"
      when: "'mariadb-server' in mysql_packages and 'focal' in ansible_distribution_release"

    - name: Add mariadb Repository Ubuntu 18.04
      apt_repository:
        repo: "deb http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.5/ubuntu bionic main"
        state: present
        filename: MariaDB
      when: "'mariadb-server' in mysql_packages and 'bionic' in ansible_distribution_release"

    - name: Add mariadb Repository Ubuntu 20.04
      apt_repository:
        repo: "deb http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.5/ubuntu focal main"
        state: present
        filename: MariaDB
      when: "'mariadb-server' in mysql_packages and 'focal' in ansible_distribution_release"

    - name: Set fact for python mysql Ubuntu 20.04
      set_fact:
        mysql_python_package_debian:
          - python3-mysqldb
          - python3-pymysql
      when: "'mariadb-server' in mysql_packages and 'focal' in ansible_distribution_release"

    - name: Set fact for python mysql Ubuntu 18.04
      set_fact:
        mysql_python_package_debian:
          - python-mysqldb
          - python3-pymysql
      when: "'mariadb-server' in mysql_packages and 'bionic' in ansible_distribution_release"
  vars:
    user_name: ubuntu
    php_version: 7.4
    mysql_packages:
      - mariadb-client
      - mariadb-server
    #ansible_python_interpreter: /usr/bin/python3
  roles:
    - hoplacloud.wordpress
